import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();

test("admin prototype navigation separates probate and enterprise functions with mock permissions", () => {
  const shell = fs.readFileSync(path.join(root, "components/admin/prototype/AdminPrototypeShell.tsx"), "utf8");
  const mockData = fs.readFileSync(path.join(root, "components/admin/prototype/mockData.ts"), "utf8");
  const prototypePage = fs.readFileSync(path.join(root, "app/internal/admin/prototype/page.tsx"), "utf8");
  const accessPage = fs.readFileSync(path.join(root, "app/internal/admin/prototype/access/page.tsx"), "utf8");
  const verificationsPage = fs.readFileSync(path.join(root, "app/internal/admin/prototype/verifications/page.tsx"), "utf8");
  const enterprisePage = fs.readFileSync(path.join(root, "app/internal/admin/prototype/enterprise/page.tsx"), "utf8");
  const prototypeDataService = fs.readFileSync(path.join(root, "components/admin/prototype/prototypeDataService.ts"), "utf8");
  const campaignsPage = fs.readFileSync(path.join(root, "app/internal/admin/prototype/campaigns/page.tsx"), "utf8");
  const caseDetailPage = fs.readFileSync(path.join(root, "app/internal/admin/prototype/cases/[caseId]/page.tsx"), "utf8");
  const licencesPage = fs.readFileSync(path.join(root, "app/internal/admin/prototype/licences/page.tsx"), "utf8");
  const organisationDetailPage = fs.readFileSync(path.join(root, "app/internal/admin/prototype/organisations/[orgId]/page.tsx"), "utf8");
  const reportsPage = fs.readFileSync(path.join(root, "app/internal/admin/prototype/reports/page.tsx"), "utf8");
  const clientInsightsPage = fs.readFileSync(path.join(root, "app/internal/admin/prototype/reports/client-insights/page.tsx"), "utf8");
  const reportFilterBar = fs.readFileSync(path.join(root, "components/admin/prototype/ReportFilterBar.tsx"), "utf8");
  const reportInsights = fs.readFileSync(path.join(root, "components/admin/prototype/reportInsights.ts"), "utf8");
  const complianceGovernance = fs.readFileSync(path.join(root, "components/admin/prototype/complianceGovernance.ts"), "utf8");
  const statusBadge = fs.readFileSync(path.join(root, "components/admin/prototype/AdminStatusBadge.tsx"), "utf8");
  const platformPrimitives = fs.readFileSync(path.join(root, "components/ui/PlatformPrimitives.tsx"), "utf8");
  const globals = fs.readFileSync(path.join(root, "app/globals.css"), "utf8");
  const routeManifest = fs.readFileSync(path.join(root, "config/routeManifest.tsx"), "utf8");

  assert.match(shell, /Probate Review/);
  assert.match(shell, /Enterprise & Licensing/);
  assert.match(shell, /Probate Operations/);
  assert.match(shell, /Operational case management and verification workflows/);
  assert.match(shell, /Organisation licensing, client portfolio insights, and reporting/);
  assert.match(shell, /function getAdminPrototypeContext/);
  assert.match(shell, /isEnterprisePath\(pathname\)/);
  assert.match(shell, /navSectionStyle\(index > 0\)/);
  assert.match(shell, /style=\{contextBadgeStyle\}/);
  assert.match(shell, /PlatformRestrictedState/);
  assert.match(shell, /WorkspaceSwitcher/);
  assert.match(shell, /lf-prototype-session-details/);
  assert.doesNotMatch(shell, /viewSwitchLinkStyle/);
  assert.match(shell, /label: "Overview"/);
  assert.match(shell, /folder_managed/);
  assert.match(shell, /verified_user/);
  assert.match(shell, /admin_panel_settings/);
  assert.match(shell, /space_dashboard/);
  assert.match(shell, /corporate_fare/);
  assert.match(shell, /bar_chart/);
  assert.match(shell, /insights/);
  assert.match(shell, /Campaigns/);
  assert.match(shell, /campaign/);
  assert.match(shell, /<Icon name="search"/);
  assert.match(shell, /lf-admin-prototype-shell/);
  assert.match(shell, /lf-admin-prototype-sidebar/);
  assert.match(shell, /lf-admin-nav-label/);
  assert.match(shell, /minHeight: 46/);
  assert.match(shell, /background: active \? "linear-gradient\(180deg, var\(--lf-bronze\) 0%, var\(--lf-bronze-strong\) 100%\)" : "#fffefd"/);
  assert.doesNotMatch(shell, /background: "#111827"|background: "#0f172a"|bg-gray-900|bg-slate-900/);
  assert.match(shell, /\/internal\/admin\/prototype\/cases/);
  assert.match(shell, /\/internal\/admin\/prototype\/verifications/);
  assert.match(shell, /\/internal\/admin\/prototype\/users/);
  assert.match(shell, /\/internal\/admin\/prototype\/access/);
  assert.match(shell, /\/internal\/admin\/prototype\/audit/);
  assert.match(shell, /\/internal\/admin\/prototype\/enterprise/);
  assert.match(shell, /\/internal\/admin\/prototype\/organisations/);
  assert.match(shell, /\/internal\/admin\/prototype\/licences/);
  assert.match(shell, /\/internal\/admin\/prototype\/campaigns/);
  assert.match(shell, /\/internal\/admin\/prototype\/reports/);
  assert.match(shell, /\/internal\/admin\/prototype\/reports\/client-insights/);

  assert.match(shell, /function getRequiredCapabilityForPath/);
  assert.match(platformPrimitives, /Access restricted/);
  assert.match(platformPrimitives, /className="lf-platform-action-row"/);
  assert.match(platformPrimitives, /className="lf-platform-section"/);
  assert.match(platformPrimitives, /className="lf-platform-stat-card"/);
  assert.match(shell, /hasAccess \? children : <AccessRestricted/);
  assert.match(shell, /Enterprise prototype — static mock data/);
  assert.match(shell, /Admin prototype — static mock data/);
  assert.match(shell, /pathname\.startsWith\("\/internal\/admin\/prototype\/enterprise"\)/);
  assert.match(shell, /pathname\.startsWith\("\/internal\/admin\/prototype\/organisations"\)/);
  assert.match(shell, /pathname\.startsWith\("\/internal\/admin\/prototype\/licences"\)/);
  assert.match(shell, /pathname\.startsWith\("\/internal\/admin\/prototype\/campaigns"\)/);
  assert.match(shell, /pathname\.startsWith\("\/internal\/admin\/prototype\/reports"\)/);
  assert.match(shell, /if \(pathname\.startsWith\("\/internal\/admin\/prototype\/enterprise"\)\) return "enterprise"/);
  assert.match(shell, /if \(pathname\.startsWith\("\/internal\/admin\/prototype\/licences"\)\) return "enterprise"/);
  assert.match(shell, /if \(pathname\.startsWith\("\/internal\/admin\/prototype\/campaigns"\)\) return "enterprise"/);
  assert.doesNotMatch(routeManifest, /\/internal\/admin|\/internal\/test-login/);

  assert.match(mockData, /role: "super_admin"/);
  assert.match(mockData, /role: "probate_admin"/);
  assert.match(mockData, /role: "enterprise_admin"/);
  assert.match(mockData, /role: "licensing_admin"/);
  assert.match(mockData, /capabilities: \["probate_review", "verification_review", "enterprise", "licensing", "reports"\]/);
  assert.match(mockData, /role: "probate_admin"[\s\S]*capabilities: \["probate_review", "verification_review"\]/);
  assert.match(mockData, /export type OrganisationUser/);
  assert.match(mockData, /lifecycleStage: "Evidence submitted" \| "Triage" \| "Manual review" \| "Decision recorded" \| "Access unlock" \| "Closed"/);
  assert.match(mockData, /executorStatus: "Not contacted" \| "Invited" \| "Verified" \| "Restricted"/);
  assert.match(mockData, /onboardingState: "Ready" \| "In rollout" \| "Needs setup" \| "Restricted"/);
  assert.match(mockData, /healthState: "Healthy" \| "Watch" \| "At risk" \| "Restricted"/);
  assert.match(mockData, /consentReadiness: "Ready" \| "Partial" \| "Blocked"/);
  assert.match(mockData, /export type LicencePlanTier = "Starter" \| "Professional" \| "Enterprise"/);
  assert.match(mockData, /export type BillingStatus/);
  assert.match(mockData, /export type LicenceStatus/);
  assert.match(mockData, /export type LicencePlan = \{/);
  assert.match(mockData, /planId: string;/);
  assert.match(mockData, /planName: string;/);
  assert.match(mockData, /planTier: LicencePlanTier;/);
  assert.match(mockData, /monthlyPrice: string;/);
  assert.match(mockData, /annualPrice: string;/);
  assert.match(mockData, /includedSeats: number;/);
  assert.match(mockData, /usedSeats: number;/);
  assert.match(mockData, /clientLimit: number;/);
  assert.match(mockData, /billingStatus: BillingStatus;/);
  assert.match(mockData, /licenceStatus: LicenceStatus;/);
  assert.match(mockData, /features: string\[\];/);
  assert.match(mockData, /export const licencePlans/);
  assert.match(mockData, /planTier: "Starter"/);
  assert.match(mockData, /planTier: "Professional"/);
  assert.match(mockData, /planTier: "Enterprise"/);
  assert.match(mockData, /function getLicencePlanForOrganisation/);
  assert.match(mockData, /function getLicenceSeatMetrics/);
  assert.match(mockData, /export const organisationUsers/);
  assert.match(mockData, /function getOrganisationUsers/);
  assert.match(mockData, /consent: \{\s*adviserInsights: boolean;\s*marketing: boolean;\s*lastUpdated: string;/);
  assert.match(mockData, /consent: \{ adviserInsights: true, marketing: true/);
  assert.match(mockData, /consent: \{ adviserInsights: false, marketing: true/);
  assert.match(reportInsights, /export type ClientOpportunityReason/);
  assert.match(reportInsights, /review_due/);
  assert.match(reportInsights, /will_outdated/);
  assert.match(reportInsights, /missing_executor/);
  assert.match(reportInsights, /incomplete_vault/);
  assert.match(reportInsights, /no_adviser_assigned/);
  assert.match(reportInsights, /high_value_band/);
  assert.match(reportInsights, /consent_missing/);
  assert.match(reportInsights, /export type ClientOpportunityScoreLevel = "blocked" \| "low" \| "medium" \| "high"/);
  assert.match(reportInsights, /scoreLevel: ClientOpportunityScoreLevel/);
  assert.match(reportInsights, /outreachReady: boolean/);
  assert.match(reportInsights, /function buildClientOpportunityScore/);
  assert.match(reportInsights, /scoreLevel: "blocked"/);
  assert.match(reportInsights, /reasons: \["consent_missing"\]/);
  assert.match(reportInsights, /Adviser insight consent required/);
  assert.match(reportInsights, /Marketing permission required/);
  assert.match(reportInsights, /function buildClientOpportunityScores/);
  assert.match(reportInsights, /function getClientOpportunityScore/);
  assert.match(reportInsights, /opportunityLevel/);
  assert.match(reportInsights, /outreachReady/);
  assert.match(reportInsights, /consentBlocked/);

  assert.match(enterprisePage, /title="Enterprise dashboard"/);
  assert.match(enterprisePage, /getEnterpriseCommandCentreData/);
  assert.match(enterprisePage, /const data = getEnterpriseCommandCentreData\(\)/);
  assert.match(enterprisePage, /Enterprise prototype — static mock data/);
  assert.match(enterprisePage, /PlatformNotice/);
  assert.match(enterprisePage, /PlatformStatCard/);
  assert.match(enterprisePage, /PlatformSection/);
  assert.match(enterprisePage, /PlatformInfoTile/);
  assert.match(enterprisePage, /PlatformChip/);
  assert.match(enterprisePage, /platformKpiGridStyle/);
  assert.match(enterprisePage, /platformInfoGridStyle/);
  assert.match(enterprisePage, /platformCtaStyle/);
  assert.match(enterprisePage, /aria-label="Operational Summary"/);
  assert.match(enterprisePage, /Organisation Health/);
  assert.match(enterprisePage, /Licensing & Usage/);
  assert.match(enterprisePage, /Reporting & Intelligence/);
  assert.match(enterprisePage, /Commercial Activity/);
  assert.match(enterprisePage, /Probate & Executor Oversight/);
  assert.match(enterprisePage, /Prototype\/Beta Features/);
  assert.match(enterprisePage, /lf-enterprise-command-centre/);
  assert.match(enterprisePage, /Enterprise command centre/);
  assert.match(enterprisePage, /Licensing & Usage/);
  assert.match(enterprisePage, /Recent organisation activity/);
  assert.match(enterprisePage, /A quiet operational feed/);
  assert.match(enterprisePage, /data\.organisationHealth\.atRisk/);
  assert.match(enterprisePage, /data\.rolloutStates\.needsSetup/);
  assert.match(enterprisePage, /activity\.detail/);
  assert.match(enterprisePage, /commandCentreStyle/);
  assert.match(enterprisePage, /gridTemplateColumns: "minmax\(0, 1\.45fr\) minmax\(320px, 0\.85fr\)"/);
  assert.match(enterprisePage, /primaryColumnStyle/);
  assert.match(enterprisePage, /secondaryColumnStyle/);
  assert.match(prototypeDataService, /getLicenceSeatMetrics/);
  assert.match(prototypeDataService, /licencePlans/);
  assert.match(prototypeDataService, /export function getEnterpriseCommandCentreData/);
  assert.match(prototypeDataService, /export function getVerificationQueueData/);
  assert.match(prototypeDataService, /export function getLicenceManagementData/);
  assert.match(prototypeDataService, /function isRenewalWarning/);
  assert.match(prototypeDataService, /function countPlansByTier/);
  assert.match(prototypeDataService, /workflowSteps/);
  assert.match(prototypeDataService, /OperationalTimelineEvent/);
  assert.match(prototypeDataService, /buildOperationalTimeline/);
  assert.match(prototypeDataService, /lifecycleCounts/);
  assert.match(prototypeDataService, /organisationHealth/);
  assert.match(prototypeDataService, /rolloutStates/);
  assert.match(prototypeDataService, /buildClientOpportunityScores/);
  assert.match(prototypeDataService, /buildReportMetrics/);
  assert.match(prototypeDataService, /buildConsentGovernanceSummary/);
  assert.match(prototypeDataService, /buildAuditPreviewEvents/);
  assert.match(prototypeDataService, /missingExecutorClients/);
  assert.match(prototypeDataService, /outdatedWillClients/);
  assert.match(prototypeDataService, /recentActivity/);
  assert.match(enterprisePage, /Licensed organisations/);
  assert.match(enterprisePage, /Active licences/);
  assert.match(enterprisePage, /Seats used/);
  assert.match(enterprisePage, /Renewals due/);
  assert.match(enterprisePage, /Consent-gated clients/);
  assert.match(enterprisePage, /Prototype only — billing not connected/);
  assert.doesNotMatch(enterprisePage, /from "@\/components\/admin\/prototype\/mockData"/);
  assert.doesNotMatch(enterprisePage, /from "@\/components\/admin\/prototype\/reportInsights"/);
  assert.match(enterprisePage, /Commercial Activity/);
  assert.match(enterprisePage, /High opportunities/);
  assert.match(enterprisePage, /Blocked by consent/);
  assert.match(enterprisePage, /Review recommended/);
  assert.match(enterprisePage, /Outreach ready/);
  assert.match(enterprisePage, /Reporting & Intelligence/);
  assert.match(enterprisePage, /Quick report filters/);
  assert.match(enterprisePage, /does not make legal decisions or validate documents/);
  assert.match(enterprisePage, /Executor and probate information remains permission-bound/);
  assert.match(enterprisePage, /data\.missingExecutorClients/);
  assert.match(enterprisePage, /data\.outdatedWillClients/);
  assert.match(enterprisePage, /Consent and compliance readiness/);
  assert.match(enterprisePage, /data\.complianceGovernance\.restrictedDataRule/);
  assert.match(enterprisePage, /data\.auditPreviewEvents\.map/);
  assert.match(prototypeDataService, /consent\.adviserInsights/);
  assert.match(enterprisePage, /Prototype\/Beta Features/);
  assert.match(enterprisePage, /\/internal\/admin\/prototype\/organisations/);
  assert.match(enterprisePage, /\/internal\/admin\/prototype\/licences/);
  assert.match(enterprisePage, /\/internal\/admin\/prototype\/reports"/);
  assert.match(enterprisePage, /\/internal\/admin\/prototype\/reports\/client-insights/);
  assert.doesNotMatch(enterprisePage, /estateValueBand|possessionsValueBand|propertyValueBand/);
  assert.match(platformPrimitives, /export function PlatformStatCard/);
  assert.match(platformPrimitives, /export function PlatformSection/);
  assert.match(platformPrimitives, /export function PlatformNotice/);
  assert.match(platformPrimitives, /export function PlatformRestrictedState/);
  assert.match(platformPrimitives, /export function PlatformActionRow/);
  assert.match(platformPrimitives, /export function PlatformEmptyState/);
  assert.match(platformPrimitives, /export function PlatformTableScroll/);
  assert.match(platformPrimitives, /export const platformPanelStyle/);
  assert.match(platformPrimitives, /export const platformSplitGridStyle/);
  assert.match(platformPrimitives, /export const platformResponsiveGridStyle/);
  assert.match(platformPrimitives, /export const platformToolbarStyle/);
  assert.match(platformPrimitives, /export const platformInputStyle/);
  assert.match(platformPrimitives, /export function PlatformInfoTile/);
  assert.match(platformPrimitives, /export function PlatformChip/);
  assert.match(platformPrimitives, /export const platformKpiGridStyle/);
  assert.match(platformPrimitives, /borderRadius: 8/);
  assert.match(platformPrimitives, /boxShadow: emphasis === "primary"/);
  assert.doesNotMatch(platformPrimitives, /#111827|#0f172a|bg-gray-900|bg-slate-900/);
  assert.match(globals, /\.lf-enterprise-command-centre/);
  assert.match(globals, /min-width: 861px\) and \(max-width: 1180px/);
  assert.match(globals, /\.lf-admin-nav-label/);
  assert.match(globals, /\.lf-platform-table-scroll/);
  assert.match(globals, /min-width: 680px/);
  assert.match(globals, /grid-template-columns: 1fr !important/);
  assert.match(globals, /max-width: 860px\)[\s\S]*\.lf-admin-prototype-sidebar nav[\s\S]*overflow-x: auto/);
  assert.match(globals, /max-width: 860px\)[\s\S]*\.lf-role-console-grid,[\s\S]*\.lf-role-console-role-grid,[\s\S]*\.lf-role-console-permissions[\s\S]*grid-template-columns: 1fr !important/);
  assert.match(globals, /max-width: 640px\)[\s\S]*\.lf-platform-action-row[\s\S]*flex-direction: column !important/);
  assert.match(globals, /max-width: 640px\)[\s\S]*\.lf-admin-prototype-content input:not\(\[type="checkbox"\]\):not\(\[type="radio"\]\),[\s\S]*\.lf-admin-prototype-content select,[\s\S]*\.lf-admin-prototype-content textarea[\s\S]*width: 100% !important/);

  assert.match(prototypePage, /PlatformStatCard/);
  assert.match(prototypePage, /PlatformSection/);
  assert.match(prototypePage, /PlatformActionRow/);
  assert.match(prototypePage, /platformKpiGridStyle/);
  assert.match(prototypePage, /platformSplitGridStyle/);
  assert.match(prototypePage, /Probate operations summary/);
  assert.match(prototypePage, /Priority cases/);
  assert.match(prototypePage, /Recent audit events/);
  assert.doesNotMatch(prototypePage, /function MetricCard/);
  assert.match(accessPage, /PlatformNotice/);
  assert.match(accessPage, /Unlock decisions require certificate validation/);

  assert.match(verificationsPage, /PlatformNotice/);
  assert.match(verificationsPage, /getVerificationQueueData/);
  assert.match(verificationsPage, /const queue = getVerificationQueueData\(\)/);
  assert.match(verificationsPage, /PlatformSection/);
  assert.match(verificationsPage, /PlatformActionRow/);
  assert.match(verificationsPage, /PlatformEmptyState/);
  assert.match(verificationsPage, /PlatformChip/);
  assert.match(verificationsPage, /Manual verification only/);
  assert.match(verificationsPage, /without automated legal decisions or access unlocks/);
  assert.match(verificationsPage, /queue\.workflowSteps\.map/);
  assert.match(verificationsPage, /queue\.groups\.map/);
  assert.match(verificationsPage, /queue\.lifecycleCounts/);
  assert.match(verificationsPage, /Executor workflow realism/);
  assert.match(verificationsPage, /queue\.operationalTimeline\.map/);
  assert.match(verificationsPage, /item\.nextAction/);
  assert.doesNotMatch(verificationsPage, /buildGroupDetail|getGroupIcon|workflowStyle|panelStyle|panelHeaderStyle/);

  assert.match(campaignsPage, /title="Campaigns"/);
  assert.match(campaignsPage, /Enterprise prototype — static mock data/);
  assert.match(campaignsPage, /platform-mediated and audit logged/);
  assert.match(campaignsPage, /will not receive unrestricted client exports/);
  assert.match(campaignsPage, /getCampaignPrototypeData/);
  assert.match(prototypeDataService, /canIncludeInOutreachAudience/);
  assert.match(prototypeDataService, /getCampaignPrototypeData/);
  assert.match(campaignsPage, /Eligible audience/);
  assert.match(campaignsPage, /Excluded by consent/);
  assert.match(campaignsPage, /Review due audience/);
  assert.match(campaignsPage, /Will update audience/);
  assert.match(campaignsPage, /Executor missing audience/);
  assert.match(campaignsPage, /Incomplete vault audience/);
  assert.match(campaignsPage, /Disabled campaign builder/);
  assert.match(campaignsPage, /Audience filter preview/);
  assert.match(campaignsPage, /Message template preview/);
  assert.match(campaignsPage, /Consent requirement checklist/);
  assert.match(campaignsPage, /Approval status checklist/);
  assert.match(campaignsPage, /label="Create campaign"/);
  assert.match(campaignsPage, /label="Export audience"/);
  assert.match(campaignsPage, /label="Send message"/);
  assert.match(campaignsPage, /label="Schedule campaign"/);
  assert.match(campaignsPage, /data\.disabledReason/);
  assert.match(prototypeDataService, /Disabled — requires consent enforcement and outreach approval/);
  assert.match(campaignsPage, /data\.auditPreviewEvents\.map/);
  assert.match(campaignsPage, /event\.actor\.displayName/);
  assert.match(prototypeDataService, /auditPreviewEvents: buildAuditPreviewEvents\("campaigns"\)/);
  assert.doesNotMatch(campaignsPage, /estateValueBand|possessionsValueBand|propertyValueBand|account_number|sort_code|document_url|private_notes|storage_path/);

  assert.match(licencesPage, /title="Licence management"/);
  assert.match(licencesPage, /getLicenceManagementData/);
  assert.match(licencesPage, /const data = getLicenceManagementData\(orgId\)/);
  assert.match(licencesPage, /PlatformTableScroll/);
  assert.doesNotMatch(licencesPage, /getLicenceSeatMetrics/);
  assert.match(licencesPage, /searchParams\?: Promise<Record<string, string \| string\[\] \| undefined>>/);
  assert.match(licencesPage, /const roleParam = typeof resolvedSearchParams\.role === "string" \? resolvedSearchParams\.role : null/);
  assert.match(licencesPage, /const canViewLicenceDetails = !roleParam \|\| roleParam === "licensing_admin" \|\| roleParam === "super_admin"/);
  assert.match(licencesPage, /Prototype only — billing not connected/);
  assert.match(licencesPage, /Licence summary cards/);
  assert.match(licencesPage, /Licensed organisations/);
  assert.match(licencesPage, /Active licences/);
  assert.match(licencesPage, /Seats used/);
  assert.match(licencesPage, /Client limit usage/);
  assert.match(licencesPage, /Renewal warnings/);
  assert.match(licencesPage, /Billing connection/);
  assert.match(licencesPage, /Organisations by licence tier/);
  assert.match(licencesPage, /Expiring renewals/);
  assert.match(licencesPage, /Seat usage warnings/);
  assert.match(licencesPage, /Plan and seat management/);
  assert.match(licencesPage, /Manage billing/);
  assert.match(licencesPage, /Upgrade plan/);
  assert.match(licencesPage, /Downgrade plan/);
  assert.match(licencesPage, /Renew licence/);
  assert.match(licencesPage, /Export invoice/);
  assert.match(licencesPage, /Licence details restricted/);
  assert.match(licencesPage, /Enterprise admins can view licence summaries/);
  assert.match(licencesPage, /Detailed plan controls require licensing admin or super admin permission/);
  assert.match(licencesPage, /disabled title="Prototype only — billing not connected"/);
  assert.match(licencesPage, /\/internal\/admin\/prototype\/licences/);
  assert.doesNotMatch(licencesPage, /stripe|invoiceUrl|payment_method|card_last4|customer_id/i);

  assert.match(organisationDetailPage, /title="Organisation not found"/);
  assert.match(organisationDetailPage, /Back to organisations/);
  assert.match(organisationDetailPage, /Licence health/);
  assert.match(organisationDetailPage, /getLicencePlanForOrganisation/);
  assert.match(organisationDetailPage, /Licence plan/);
  assert.match(organisationDetailPage, /Client limit/);
  assert.match(organisationDetailPage, /Billing status/);
  assert.match(organisationDetailPage, /features\.map/);
  assert.match(organisationDetailPage, /\/internal\/admin\/prototype\/licences\?orgId=\$\{org\.id\}/);
  assert.match(organisationDetailPage, /Prototype only — billing not connected/);
  assert.match(organisationDetailPage, /Adviser \/ user panel/);
  assert.match(organisationDetailPage, /Client portfolio/);
  assert.match(organisationDetailPage, /Portfolio opportunity/);
  assert.match(organisationDetailPage, /buildClientOpportunityScores/);
  assert.match(organisationDetailPage, /getClientOpportunityScore/);
  assert.match(organisationDetailPage, /High opportunity clients/);
  assert.match(organisationDetailPage, /Medium opportunity clients/);
  assert.match(organisationDetailPage, /Blocked by consent/);
  assert.match(organisationDetailPage, /Outreach ready/);
  assert.match(organisationDetailPage, /<Th>Opportunity<\/Th>/);
  assert.match(organisationDetailPage, /<Th>Outreach<\/Th>/);
  assert.match(organisationDetailPage, /<Th>Blockers<\/Th>/);
  assert.match(organisationDetailPage, /Consent & compliance/);
  assert.match(organisationDetailPage, /Reporting shortcuts/);
  assert.match(organisationDetailPage, /Audit \/ activity preview/);
  assert.match(organisationDetailPage, /Reports exclude clients without adviser insight consent/);
  assert.match(organisationDetailPage, /client\.consent\.adviserInsights/);
  assert.match(organisationDetailPage, /client\.consent\.marketing/);
  assert.match(organisationDetailPage, /\/internal\/admin\/prototype\/licences/);
  assert.match(organisationDetailPage, /\/internal\/admin\/prototype\/reports\?orgId=\$\{org\.id\}/);
  assert.match(organisationDetailPage, /\/internal\/admin\/prototype\/reports\/client-insights\?orgId=\$\{org\.id\}/);
  assert.match(organisationDetailPage, /estateValueBand/);
  assert.match(organisationDetailPage, /possessionsValueBand/);
  assert.doesNotMatch(organisationDetailPage, /account_number|sort_code|document_url|private_notes|storage_path/);

  assert.match(reportsPage, /searchParams\?: Promise<Record<string, string \| string\[\] \| undefined>>/);
  assert.match(reportsPage, /const filters = getReportFilters\(resolvedSearchParams\)/);
  assert.match(reportsPage, /const orgId = filters\.orgId/);
  assert.match(reportsPage, /getReportPrototypeData/);
  assert.match(reportsPage, /const data = getReportPrototypeData\(filters, "reports"\)/);
  assert.match(reportsPage, /<ReportFilterBar/);
  assert.doesNotMatch(reportsPage, /from "@\/components\/admin\/prototype\/mockData"/);
  assert.doesNotMatch(reportsPage, /filterOrganisationClients,\n|buildClientInsights,\n|buildClientOpportunityScores,\n|getReportableClients,\n|getConsentBlockedCount,\n|getActiveFilterChips,\n/);
  assert.match(reportsPage, /buildClientInsightsHref\(filters, data\.selectedOrganisation\?\.id\)/);
  assert.match(reportsPage, /Back to organisations/);
  assert.match(reportsPage, /Clients in scope/);
  assert.match(reportsPage, /Client insights and outreach depend on explicit client consent/);
  assert.match(reportsPage, /Clients needing review \(consented only\)/);
  assert.match(reportsPage, /Clients missing consent/);
  assert.match(reportsPage, /Incomplete vaults \(consented only\)/);
  assert.match(reportsPage, /Missing executors \(consented only\)/);
  assert.match(reportsPage, /Adviser insight consent/);
  assert.match(reportsPage, /Marketing permission/);
  assert.match(reportsPage, /Will outdated/);
  assert.match(reportsPage, /Critical insights/);
  assert.match(reportsPage, /Portfolio opportunity/);
  assert.match(reportsPage, /Compliance governance/);
  assert.match(reportsPage, /data\.governance\.exportReason/);
  assert.match(reportsPage, /High opportunity clients/);
  assert.match(reportsPage, /Medium opportunity clients/);
  assert.match(reportsPage, /Blocked by consent/);
  assert.match(reportsPage, /Outreach-ready clients/);
  assert.match(reportsPage, /opportunityLevel: getSingleQueryValue\(searchParams\?\.opportunityLevel\)/);
  assert.match(reportsPage, /outreachReady: getSingleQueryValue\(searchParams\?\.outreachReady\)/);
  assert.match(reportsPage, /consentBlocked: getSingleQueryValue\(searchParams\?\.consentBlocked\)/);
  assert.doesNotMatch(reportsPage, /account_number|sort_code|document_url|private_notes|storage_path/);

  assert.match(clientInsightsPage, /searchParams\?: Promise<Record<string, string \| string\[\] \| undefined>>/);
  assert.match(clientInsightsPage, /const filters = getReportFilters\(resolvedSearchParams\)/);
  assert.match(clientInsightsPage, /const orgId = filters\.orgId/);
  assert.match(clientInsightsPage, /getReportPrototypeData/);
  assert.match(clientInsightsPage, /const data = getReportPrototypeData\(filters, "client_insights"\)/);
  assert.match(clientInsightsPage, /<ReportFilterBar/);
  assert.doesNotMatch(clientInsightsPage, /from "@\/components\/admin\/prototype\/mockData"/);
  assert.doesNotMatch(clientInsightsPage, /filterOrganisationClients,\n|buildClientInsights,\n|buildClientOpportunityScores,\n|getConsentBlockedCount,\n/);
  assert.match(clientInsightsPage, /getClientOpportunityScore/);
  assert.match(clientInsightsPage, /getClientInsightSummary/);
  assert.match(clientInsightsPage, /Client insights and outreach depend on explicit client consent/);
  assert.match(clientInsightsPage, /PlatformNotice/);
  assert.match(clientInsightsPage, /PlatformTableScroll/);
  assert.match(clientInsightsPage, /Consent, export, and audit controls/);
  assert.match(clientInsightsPage, /client\.consent\.adviserInsights \? "Allowed" : "Consent required"/);
  assert.match(clientInsightsPage, /Client has not granted adviser insight access/);
  assert.match(clientInsightsPage, /Contact clients — Disabled — requires consent enforcement and outreach approval/);
  assert.match(clientInsightsPage, /Run campaign — Disabled — requires consent enforcement and outreach approval/);
  assert.match(clientInsightsPage, /allowedInsights/);
  assert.match(clientInsightsPage, /insight\.insightType !== "consent_missing"/);
  assert.match(clientInsightsPage, /client\.consent\.marketing/);
  assert.match(clientInsightsPage, /client\.consent\.lastUpdated/);
  assert.match(clientInsightsPage, /Insight signal engine/);
  assert.match(clientInsightsPage, /Opportunity side panel preview/);
  assert.match(clientInsightsPage, /future client drill-in/);
  assert.match(clientInsightsPage, /Opportunity/);
  assert.match(clientInsightsPage, /Outreach/);
  assert.match(clientInsightsPage, /Blockers/);
  assert.match(clientInsightsPage, /Reasons:/);
  assert.match(clientInsightsPage, /Next step:/);
  assert.match(clientInsightsPage, /opportunityLevel: getSingleQueryValue\(searchParams\?\.opportunityLevel\)/);
  assert.match(clientInsightsPage, /outreachReady: getSingleQueryValue\(searchParams\?\.outreachReady\)/);
  assert.match(clientInsightsPage, /consentBlocked: getSingleQueryValue\(searchParams\?\.consentBlocked\)/);
  assert.match(clientInsightsPage, /Back to organisations/);
  assert.match(clientInsightsPage, /data\.filteredClients\.map/);
  assert.match(clientInsightsPage, /estateValueBand/);
  assert.doesNotMatch(clientInsightsPage, /account_number|sort_code|document_url|private_notes|storage_path/);

  assert.match(complianceGovernance, /export function buildConsentGovernanceSummary/);
  assert.match(complianceGovernance, /export function buildAuditPreviewEvents/);
  assert.match(complianceGovernance, /export function canShowDetailedInsights/);
  assert.match(complianceGovernance, /export function canIncludeInOutreachAudience/);
  assert.match(complianceGovernance, /Exports are disabled until consent enforcement/);
  assert.match(complianceGovernance, /Only consent-cleared, banded, non-document signals/);

  assert.match(reportFilterBar, /"use client"/);
  assert.match(reportFilterBar, /Report filters/);
  assert.match(reportFilterBar, /filter_alt/);
  assert.match(reportFilterBar, /router\.replace/);
  assert.match(reportFilterBar, /Run report/);
  assert.match(reportFilterBar, /runReport/);
  assert.match(reportFilterBar, /Report run for/);
  assert.match(reportFilterBar, /Filters changed\. Run report/);
  assert.match(reportFilterBar, /Clear all/);
  assert.match(reportFilterBar, /All organisations/);
  assert.match(reportFilterBar, /Active report filters/);

  assert.match(reportInsights, /export type ClientInsightType/);
  assert.match(reportInsights, /missing_executor/);
  assert.match(reportInsights, /will_outdated/);
  assert.match(reportInsights, /review_due/);
  assert.match(reportInsights, /incomplete_vault/);
  assert.match(reportInsights, /no_adviser/);
  assert.match(reportInsights, /consent_missing/);
  assert.match(reportInsights, /filterOrganisationClients/);
  assert.match(reportInsights, /getReportableClients/);
  assert.match(reportInsights, /getConsentBlockedCount/);
  assert.match(reportInsights, /buildClientInsights/);
  assert.match(reportInsights, /buildReportMetrics/);
  assert.match(reportInsights, /highOpportunity/);
  assert.match(reportInsights, /mediumOpportunity/);
  assert.match(reportInsights, /blockedOpportunity/);
  assert.match(reportInsights, /outreachReady/);
  assert.match(reportInsights, /if \(!hasAdviserInsightConsent\(client\)\)/);
  assert.match(reportInsights, /message: "Client has not granted adviser insight access"/);
  assert.match(reportInsights, /if \(!hasAdviserInsightConsent\(client\)\) return "Consent required"/);
  assert.match(reportInsights, /clientsInScope: clients\.length/);

  assert.match(accessPage, /owner-invited vault access from death-certificate probate unlock decisions/);
  assert.match(accessPage, /Owner invitation/);
  assert.match(accessPage, /Death certificate submission/);
  assert.match(accessPage, /Validation and unlock/);
  assert.match(accessPage, /they cannot directly edit an individual vault/);
  assert.match(accessPage, /Confirm unlock|Validate evidence/);

  assert.match(caseDetailPage, /Validate certificate/);
  assert.match(caseDetailPage, /Confirm limited unlock/);
  assert.match(caseDetailPage, /Limited vault unlock model/);
  assert.match(caseDetailPage, /No owner settings, billing, account editing, contacts editing, or unrestricted vault edits/);
  assert.match(reportInsights, /client\.consent\.adviserInsights === true/);
  assert.match(reportInsights, /client\.consent\.marketing === true/);
  assert.match(reportInsights, /estateValueBand/);
  assert.doesNotMatch(reportInsights, /account_number|sort_code|document_url|private_notes|storage_path/);

  assert.match(statusBadge, /Consent allowed/);
  assert.match(statusBadge, /Consent required/);
  assert.match(statusBadge, /Static mock data/);
  assert.match(statusBadge, /Restricted/);
  assert.match(statusBadge, /check_circle/);
  assert.match(statusBadge, /block/);
  assert.match(statusBadge, /science/);
  assert.match(globals, /lf-admin-prototype-shell/);
  assert.match(globals, /lf-admin-prototype-sidebar a:hover/);
  assert.match(globals, /lf-admin-prototype-content tbody tr:hover/);
  assert.match(globals, /lf-admin-prototype-content button:disabled/);
  assert.match(globals, /max-width: 860px/);
  assert.doesNotMatch(globals, /lf-admin-prototype-shell[\s\S]{0,220}#111827/);
});
