import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();

test("dashboard overview cards use compact shared summary cards with icon-only review actions", () => {
  const dashboardPage = fs.readFileSync(path.join(root, "app/(app)/dashboard/page.tsx"), "utf8");
  const summaryCard = fs.readFileSync(path.join(root, "app/(app)/components/dashboard/DashboardAssetSummaryCard.tsx"), "utf8");
  const actionQueue = fs.readFileSync(path.join(root, "app/(app)/components/dashboard/ActionQueuePanel.tsx"), "utf8");
  const dashboardRender = dashboardPage.slice(
    dashboardPage.indexOf('return (\n    <div className="lf-dashboard-shell" style={{ display: "grid", gap: 14 }}>'),
    dashboardPage.indexOf("function ReadinessSnapshot"),
  );

  assert.match(dashboardPage, /value=\{String\(financeRecordCount\)\}/);
  assert.match(dashboardPage, /value=\{String\(propertyRecordCount\)\}/);
  assert.match(dashboardPage, /value=\{String\(businessRecordCount\)\}/);
  assert.doesNotMatch(dashboardPage, /value=\{financialSummary\.valueText\}/);
  assert.doesNotMatch(dashboardPage, /value=\{propertySummary\.valueText\}/);
  assert.doesNotMatch(dashboardPage, /value=\{businessSummary\.valueText\}/);
  assert.match(dashboardPage, /function useDashboardState\(input: DashboardStateInput\): DashboardState/);
  assert.match(dashboardPage, /<ActionQueuePanel items=\{dashboardState\.actions\.items\} context=\{dashboardState\.actions\.context\} onAction=\{handleAction\} \/>/);
  assert.match(dashboardPage, /className="lf-dashboard-shell"/);
  assert.match(dashboardPage, /className="lf-dashboard-overview-panel"/);
  assert.match(dashboardPage, /className="lf-content-grid lf-dashboard-overview-grid"/);
  assert.match(dashboardPage, /className="lf-dashboard-readiness-summary"/);
  assert.match(dashboardPage, /className="lf-dashboard-readiness-heading"/);
  assert.match(dashboardPage, /className="lf-dashboard-readiness-card"/);
  assert.match(dashboardPage, /className="lf-dashboard-readiness-task-list"/);
  assert.match(dashboardPage, /className="lf-dashboard-readiness-task"/);
  assert.match(dashboardPage, /className="lf-dashboard-review-panel"/);
  assert.match(dashboardPage, /function filterConsumerDashboardBlockers/);
  assert.match(dashboardPage, /requiredRole !== "admin"/);
  assert.match(dashboardPage, /!item\.href\.startsWith\("\/internal\/"\)/);
  assert.match(dashboardPage, /type DashboardContactRow = \{/);
  assert.match(dashboardPage, /role: DashboardContactRole/);
  assert.match(dashboardPage, /status: DashboardContactStatus/);
  assert.match(dashboardPage, /actions: DashboardContactAction\[\]/);
  assert.match(dashboardPage, /function normalizeDashboardContactRows/);
  assert.match(dashboardPage, /contacts: \{\s*rows: normalizedContactRows,/);
  assert.match(dashboardPage, /documents: \{\s*items: dashboardDocumentItems,\s*storedCount: storedDocumentCount,/);
  assert.match(dashboardPage, /const documentCoverage = useMemo/);
  assert.match(dashboardPage, /coverage: documentCoverage/);
  assert.match(dashboardPage, /type ExecutorLegalReadinessModel = \{/);
  assert.match(dashboardPage, /type ExecutorLegalReadinessStatusLevel = "Not started" \| "Incomplete" \| "At risk" \| "Ready"/);
  assert.match(dashboardPage, /executorAssigned: boolean/);
  assert.match(dashboardPage, /executorAccepted: boolean/);
  assert.match(dashboardPage, /willPresent: boolean/);
  assert.match(dashboardPage, /willUploaded: boolean/);
  assert.match(dashboardPage, /keyDocumentsPresent: boolean/);
  assert.match(dashboardPage, /supportingLegalInfoPresent: boolean/);
  assert.match(dashboardPage, /powerOfAttorneyPresent: boolean/);
  assert.match(dashboardPage, /contactsComplete: boolean/);
  assert.match(dashboardPage, /identityVerified: boolean/);
  assert.match(dashboardPage, /function buildExecutorLegalReadinessState/);
  assert.match(dashboardPage, /function getExecutorLegalReadinessStatusLevel/);
  assert.match(dashboardPage, /if \(!model\.executorAssigned\) return "Not started"/);
  assert.match(dashboardPage, /if \(!model\.willPresent && !model\.willUploaded\) return "Incomplete"/);
  assert.match(dashboardPage, /return "At risk"/);
  assert.match(dashboardPage, /return "Ready"/);
  assert.match(dashboardPage, /legalReadiness: \{/);
  assert.match(dashboardPage, /Estate Readiness/);
  assert.match(dashboardPage, /ReadinessSnapshot/);
  assert.match(dashboardPage, /ReadinessUploadAction/);
  assert.match(dashboardPage, /executorSummary/);
  assert.match(dashboardPage, /documentSummary/);
  assert.match(dashboardPage, /supportingLegalInfo: supportingLegalInfoPresent \? "Recorded" : "Not added"/);
  assert.match(dashboardPage, /powerOfAttorney: powerOfAttorneyPresent \? "Recorded" : "Not added"/);
  assert.match(dashboardPage, /function hasSupportingLegalInfoRecord/);
  assert.match(dashboardPage, /function hasPowerOfAttorneyRecord/);
  assert.match(dashboardPage, /reviewRecommended/);
  assert.match(dashboardPage, /Review recommended/);
  assert.match(dashboardPage, /function renderReadinessActionPanel/);
  assert.match(dashboardPage, /readinessKey: "willUploaded"/);
  assert.match(dashboardPage, /const requiredReadinessTasks = dashboardState\.legalReadiness\.items\.filter\(\(item\) => !item\.complete\)/);
  assert.match(dashboardPage, /Required estate readiness tasks/);
  assert.match(dashboardPage, /Required tasks/);
  assert.match(dashboardPage, /Open task/);
  assert.match(dashboardPage, /router\.push\(dashboardState\.legalReadiness\.nextAction\.href\)/);
  assert.match(dashboardPage, /router\.push\(item\.href\)/);
  assert.match(dashboardPage, /readinessTaskButtonStyle/);
  assert.doesNotMatch(dashboardPage, /buildReviewPanelFromReadinessItem/);
  assert.match(dashboardPage, /Full contact management/);
  assert.match(dashboardPage, /Upload identity document/);
  assert.match(dashboardPage, /Upload financial\/property document/);
  assert.match(dashboardPage, /<AttachmentGallery[\s\S]*items=\{dashboardState\.documents\.items\}/);
  assert.match(dashboardPage, /Multiple files are supported there/);
  assert.match(dashboardPage, /Mark reviewed is not stored separately yet/);
  assert.match(dashboardPage, /not legal advice/);
  assert.match(dashboardPage, /does not validate legal authenticity/);
  assert.doesNotMatch(dashboardPage, /valid legal document|legally valid|legally binding/);
  assert.match(dashboardPage, /DASHBOARD_KEY_DOCUMENT_CATEGORIES/);
  assert.match(dashboardPage, /No documents uploaded yet\./);
  assert.match(dashboardPage, /Only 1 document uploaded/);
  assert.match(dashboardPage, /Key documents missing:/);
  assert.match(dashboardPage, /<AttachmentGallery[\s\S]*items=\{dashboardState\.documents\.items\}/);
  assert.match(dashboardPage, /completeness: \{\s*items: vaultCompletenessItems,/);
  assert.match(dashboardPage, /blockers: \{\s*items: blockingState\.filter/);
  assert.match(dashboardPage, /signals: DashboardInsightSignal\[\]/);
  assert.match(dashboardPage, /function buildDashboardInsightSignals/);
  assert.doesNotMatch(dashboardPage, /const handleSetupStepAction = useCallback/);
  assert.doesNotMatch(dashboardPage, /function buildReviewPanelFromSetupStep/);
  assert.doesNotMatch(dashboardPage, /<a key=\{step\.key\} href=\{step\.href\}/);
  assert.doesNotMatch(dashboardPage, /href=\{dashboardState\.actions\.nextSetupStep\.href\}/);
  assert.match(dashboardPage, /type: "missing_executor"/);
  assert.match(dashboardPage, /type: "missing_will"/);
  assert.match(dashboardPage, /type: "profile_incomplete"/);
  assert.match(dashboardPage, /type: "missing_financial_records"/);
  assert.match(dashboardPage, /type: "missing_documents"/);
  assert.match(dashboardPage, /type: "review_overdue"/);
  assert.match(dashboardPage, /const handleAction = useCallback\(\(actionKey: string\)/);
  assert.match(dashboardPage, /deriveBlockingState\(/);
  assert.match(dashboardPage, /inlineSummary/);
  assert.match(dashboardPage, /hideItems/);
  assert.match(dashboardPage, /actionIcon="open_in_new"/);
  assert.match(summaryCard, /<IconButton/);
  assert.match(summaryCard, /actionIcon = "open_in_new"/);
  assert.match(summaryCard, /className="lf-dashboard-summary-value" style=\{valueStyle\}/);
  assert.match(summaryCard, /className="lf-dashboard-summary-detail" style=\{detailStyle\}/);
  assert.match(actionQueue, /Action Centre/);
  assert.match(actionQueue, /className="lf-action-centre"/);
  assert.match(actionQueue, /className="lf-action-centre-header"/);
  assert.match(actionQueue, /className="lf-action-centre-intro"/);
  assert.match(actionQueue, /className="lf-action-centre-section"/);
  assert.match(actionQueue, /className="lf-action-centre-section-title-row"/);
  assert.match(actionQueue, /className="lf-action-centre-section-summary"/);
  assert.match(actionQueue, /className="lf-action-centre-row"/);
  assert.match(actionQueue, /className="lf-action-centre-row-badges"/);
  assert.match(actionQueue, /className="lf-action-centre-row-actions"/);
  assert.match(actionQueue, /Critical actions/);
  assert.match(actionQueue, /Recommended actions/);
  assert.match(actionQueue, /Your tasks/);
  assert.match(actionQueue, /Things to do,\s*reminders, and user-created tasks live here instead of the dashboard overview/);
  assert.match(actionQueue, /Completed/);
  assert.match(actionQueue, /type ActionCentreTaskType = "user_created" \| "system_generated" \| "reminder"/);
  assert.match(actionQueue, /relatedEntity\?: string/);
  assert.match(actionQueue, /createdAt\?: string \| null/);
  assert.match(actionQueue, /task:complete:\$\{task\.id\}/);
  assert.match(actionQueue, /task:open:\$\{task\.id\}/);
  assert.match(actionQueue, /function taskDuplicatesAction/);
  assert.match(actionQueue, /task\.type !== "system_generated"/);
  assert.match(actionQueue, /function getTaskDedupeKey/);
  assert.match(dashboardPage, /relatedEntity: String\(metadata\["related_asset_label"\]/);
  assert.doesNotMatch(dashboardPage, /showTaskCard/);
  assert.doesNotMatch(dashboardPage, /taskSummary/);
  assert.doesNotMatch(dashboardPage, /title="Tasks"/);
  assert.match(dashboardPage, /showFinancialCard \|\| showLegalCard \|\| showPropertyCard \|\| showBusinessCard \|\| showDigitalCard \|\| showPossessionsCard/);
  assert.doesNotMatch(dashboardPage, /showFinancialCard \|\| showLegalCard \|\| showPropertyCard \|\| showBusinessCard \|\| showDigitalCard \|\| showPossessionsCard \|\| showTaskCard/);
  assert.match(dashboardPage, /categoryKey !== "tasks"/);
  assert.match(dashboardPage, /markDashboardTaskComplete/);
  assert.match(dashboardPage, /tasks: actionCentreTasks/);
  assert.match(actionQueue, /All up to date/);
  assert.match(actionQueue, /notifications_active/);
  assert.match(actionQueue, /contacts still need to accept invitations\./);
  assert.match(actionQueue, /contacts are ready for invite emails\./);
  assert.match(actionQueue, /assignment_late/);
  assert.match(actionQueue, /stageChipStyle/);
  assert.match(actionQueue, /buildSectionSummary/);
  assert.match(actionQueue, /type ActionPriorityLevel = "Critical" \| "High" \| "Medium" \| "Low"/);
  assert.match(actionQueue, /dashboard-add-executor/);
  assert.match(actionQueue, /estateReadiness/);
  assert.match(actionQueue, /dashboard-upload-will/);
  assert.match(actionQueue, /dashboard-add-key-documents/);
  assert.match(actionQueue, /Will information is a core readiness signal/);
  assert.match(actionQueue, /return "will"/);
  assert.match(actionQueue, /return "key-documents"/);
  assert.match(actionQueue, /priorityPillStyle/);
  assert.match(actionQueue, /aria-expanded=\{isOpen\}/);
  assert.match(actionQueue, /useState<ActionCentreSection\["key"\] \| null \| undefined>\(undefined\)/);
  assert.match(actionQueue, /effectiveOpenSectionKey = openSectionKey === undefined \? initialOpenSectionKey : openSectionKey/);
  assert.match(actionQueue, /toggleSection\(section\.key\)/);
  assert.match(actionQueue, /onAction\(item.actionKey\)/);
  assert.doesNotMatch(actionQueue, /supportingLegalInfoPresent|powerOfAttorneyPresent/);
  assert.doesNotMatch(dashboardPage, /ContactInvitationManager mode="dashboard"/);
  assert.doesNotMatch(dashboardPage, /overallVaultProgress/);
  assert.doesNotMatch(dashboardPage, /progressTrackStyle/);
  assert.doesNotMatch(dashboardPage, /% ready|% complete/);
  assert.match(dashboardPage, /storedDocumentCount/);
  assert.match(dashboardRender, /<h2 style=\{\{ margin: 0, fontSize: 18 \}\}>Overview<\/h2>/);
  assert.match(dashboardRender, /<ActionQueuePanel items=\{dashboardState\.actions\.items\} context=\{dashboardState\.actions\.context\} onAction=\{handleAction\} \/>/);
  assert.match(dashboardRender, /aria-label="Estate readiness summary"/);
  assert.doesNotMatch(dashboardRender, /Get started with your vault/);
  assert.doesNotMatch(dashboardRender, /<h2 style=\{\{ margin: 0, fontSize: 18 \}\}>Next steps<\/h2>/);
  assert.doesNotMatch(dashboardRender, /People you trust/);
  assert.doesNotMatch(dashboardRender, /aria-label="Vault completeness"/);
  assert.doesNotMatch(dashboardRender, /aria-label="Recent documents"/);
  assert.doesNotMatch(dashboardRender, /setupStepsGridStyle|completenessGridStyle|documentCategoryGridStyle|readinessGridStyle/);
  assert.doesNotMatch(dashboardRender, /<ReadinessSnapshot|<ReadinessUploadAction|<AttachmentGallerySummary|<AttachmentGallery\s/);
  assert.ok(dashboardRender.indexOf(">Overview<") < dashboardRender.indexOf("<ActionQueuePanel"));
  assert.ok(dashboardRender.indexOf("<ActionQueuePanel") < dashboardRender.indexOf('aria-label="Estate readiness summary"'));
});

test("contacts keeps the fuller invitation management view while dashboard stays compact", () => {
  const contactsWorkspace = fs.readFileSync(path.join(root, "components/contacts/ContactsNetworkWorkspace.tsx"), "utf8");
  const invitationManager = fs.readFileSync(path.join(root, "app/(app)/components/dashboard/ContactInvitationManager.tsx"), "utf8");

  assert.match(contactsWorkspace, /<ContactInvitationManager[\s\S]*mode="full"[\s\S]*selectedContactId=\{selectedContactId\}[\s\S]*selectedContactProfile=\{selectedContact\}[\s\S]*\/>/);
  assert.match(invitationManager, /mode\?: "full" \| "dashboard"/);
  assert.match(invitationManager, /selectedContactId\?: string/);
  assert.match(invitationManager, /Owner notes/);
  assert.match(invitationManager, /Open Contacts/);
  assert.match(invitationManager, /buildContactsWorkspaceHref/);
  assert.doesNotMatch(invitationManager, /Invitation sent and awaiting activation/);
  assert.doesNotMatch(invitationManager, /Signed in and verified\./);
  assert.doesNotMatch(invitationManager, />Resend<\/th>/);
  assert.match(invitationManager, /function canSendInvite/);
  assert.match(invitationManager, /function canResendInvite/);
});

test("shared attachment gallery uses icon buttons with tooltips instead of ad hoc text action buttons", () => {
  const attachmentGallery = fs.readFileSync(path.join(root, "components/documents/AttachmentGallery.tsx"), "utf8");
  const css = fs.readFileSync(path.join(root, "app/globals.css"), "utf8");
  const actionQueue = fs.readFileSync(path.join(root, "app/(app)/components/dashboard/ActionQueuePanel.tsx"), "utf8");

  assert.match(attachmentGallery, /className="lf-attachment-gallery"/);
  assert.match(attachmentGallery, /className="lf-attachment-card-main"/);
  assert.match(attachmentGallery, /className="lf-attachment-actions"/);
  assert.match(attachmentGallery, /className=\{danger \? "lf-attachment-action is-danger" : "lf-attachment-action"\}/);
  assert.match(actionQueue, /className="lf-action-centre"/);
  assert.match(actionQueue, /className="lf-action-centre-section"/);
  assert.match(actionQueue, /className="lf-action-centre-row"/);
  assert.match(actionQueue, /className="lf-action-centre-row-actions"/);
  assert.match(css, /\.lf-topbar \{[\s\S]*display: grid;[\s\S]*grid-template-columns: minmax\(0, 1fr\) auto/);
  assert.match(css, /\.lf-topbar-user \{[\s\S]*width: 44px;[\s\S]*height: 44px;[\s\S]*flex: 0 0 44px/);
  assert.match(css, /\.lf-topbar-user-copy \{[\s\S]*display: none/);
  assert.match(css, /max-width: 1100px\)[\s\S]*\.lf-topbar[\s\S]*grid-template-columns: 44px minmax\(0, 1fr\) auto/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-topbar[\s\S]*grid-template-columns: 44px minmax\(0, 1fr\) 44px/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-topbar-actions[\s\S]*display: flex/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-topbar-actions \.lf-workspace-switcher,[\s\S]*\.lf-topbar-security[\s\S]*display: none !important/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-topbar-user[\s\S]*width: 44px/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-topbar-user-copy[\s\S]*display: none/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-mobile-drawer \.lf-workspace-switcher[\s\S]*display: block/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-dashboard-overview-grid[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /max-width: 374px\)[\s\S]*\.lf-dashboard-overview-grid[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-action-centre-intro[\s\S]*display: none !important/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-action-centre-section-summary[\s\S]*-webkit-line-clamp: 1/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-content-grid[\s\S]*grid-template-columns: 1fr !important/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-content-wrap,[\s\S]*\.lf-main-content,[\s\S]*\.lf-main-content > \*[\s\S]*min-width: 0/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-topbar[\s\S]*overflow: hidden/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-dashboard-summary-card[\s\S]*width: 100% !important/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-dashboard-summary-card[\s\S]*grid-template-rows: auto auto !important/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-dashboard-summary-card[\s\S]*max-width: 100% !important/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-dashboard-summary-title[\s\S]*white-space: nowrap/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-dashboard-summary-card > \*[\s\S]*min-width: 0/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-main-content input:not\(\[type="checkbox"\]\):not\(\[type="radio"\]\),[\s\S]*\.lf-main-content select,[\s\S]*\.lf-main-content textarea[\s\S]*min-width: 0 !important/);
  assert.match(css, /max-width: 700px\)[\s\S]*\.lf-link-btn,[\s\S]*\.lf-primary-btn[\s\S]*min-height: 44px/);
  assert.match(css, /@media \(max-width: 700px\)[\s\S]*\.lf-action-centre-row-actions/);
  assert.match(css, /\.lf-action-centre-row-actions > button,[\s\S]*min-height: 44px !important/);
  assert.match(css, /\.lf-attachment-actions[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(css, /@media \(max-width: 420px\)[\s\S]*\.lf-attachment-card-main[\s\S]*flex-direction: column !important/);
  assert.match(attachmentGallery, /function AttachmentVisual/);
  assert.match(attachmentGallery, /function AttachmentActionButton/);
  assert.match(attachmentGallery, /label="View"/);
  assert.match(attachmentGallery, /label="Download"/);
  assert.match(attachmentGallery, /label="Print"/);
  assert.match(attachmentGallery, /label="Replace"/);
  assert.match(attachmentGallery, /label="Remove"/);
  assert.match(attachmentGallery, /icon="visibility"/);
  assert.match(attachmentGallery, /icon="download"/);
  assert.match(attachmentGallery, /icon="open_in_new"/);
  assert.match(attachmentGallery, /icon="print"/);
  assert.match(attachmentGallery, /icon="delete"/);
  assert.match(attachmentGallery, /alt=\{visual\.alt\}/);
  assert.match(attachmentGallery, /kind === "image"/);
  assert.match(attachmentGallery, /kind === "pdf"/);
  assert.match(attachmentGallery, /kind === "word"/);
  assert.match(attachmentGallery, /kind === "spreadsheet"/);
  assert.match(attachmentGallery, /kind === "calendar"/);
  assert.match(attachmentGallery, /getFileIcon/);
  assert.match(attachmentGallery, /picture_as_pdf/);
  assert.match(attachmentGallery, /article/);
  assert.match(attachmentGallery, /table_chart/);
  assert.match(attachmentGallery, /calendar_month/);
  assert.match(attachmentGallery, /fileTypePillStyle/);
  assert.match(attachmentGallery, /statusLabel/);
  assert.match(attachmentGallery, /Uploaded \{formatDate\(item\.createdAt\)\}/);
  assert.doesNotMatch(attachmentGallery, /window\.open/);
  assert.doesNotMatch(attachmentGallery, /<IconButton/);
  assert.doesNotMatch(attachmentGallery, /style=\{miniGhostBtn\}/);
});

test("dashboard profile chip signs the avatar through the authenticated server route", () => {
  const layout = fs.readFileSync(path.join(root, "app/(app)/layout.tsx"), "utf8");
  const route = fs.readFileSync(path.join(root, "app/api/profile/identity-chip/route.ts"), "utf8");
  const avatarRoute = fs.readFileSync(path.join(root, "app/api/profile/avatar/route.ts"), "utf8");

  assert.match(layout, /loadServerProfileIdentityChip\(email\)[\s\S]*loadProfileIdentityChip\(supabase, \{ userId, email \}\)/);
  assert.match(layout, /const fallbackProfile = !serverProfile\?\.avatarUrl/);
  assert.match(layout, /avatarUrl: serverProfile\?\.avatarUrl \|\| fallbackProfile\?\.avatarUrl \|\| ""/);
  assert.match(layout, /const setFreshAvatarUrl = useCallback/);
  assert.match(layout, /readCachedProfileAvatarUrl\(\)/);
  assert.match(layout, /PROFILE_AVATAR_CACHE_KEY/);
  assert.match(layout, /ignored_empty_value=yes/);
  assert.match(layout, /cacheProfileAvatarUrl\(next\)/);
  assert.match(layout, /hydrateUserChip\(userId, nextEmail, mounted, setDisplayName, setTelephone, setInitials, setFreshAvatarUrl\)/);
  assert.doesNotMatch(layout, /failedAvatarUrl/);
  assert.doesNotMatch(layout, /avatarRetryKey/);
  assert.doesNotMatch(layout, /recoverSidebarAvatar/);
  assert.doesNotMatch(layout, /setFailedAvatarUrl\(renderedAvatarUrl\)/);
  assert.match(layout, /backgroundImage: `url\("\$\{cssEscapeUrl\(renderedAvatarUrl\)\}"\)`/);
  assert.match(layout, /const \[confirmedAvatarUrl, setConfirmedAvatarUrl\] = useState\(""\)/);
  assert.match(layout, /const image = new Image\(\)/);
  assert.match(layout, /image\.onload = \(\) => \{/);
  assert.match(layout, /setConfirmedAvatarUrl\(effectiveAvatarUrl\)/);
  assert.match(layout, /image\.onerror = \(\) => \{/);
  assert.match(layout, /data-avatar-ready=\{renderedAvatarUrl \? "true" : "false"\}/);
  assert.match(layout, /className="lf-topbar-user-avatar-fallback"/);
  assert.doesNotMatch(layout, /className="lf-topbar-user-avatar-img"/);
  assert.match(layout, /function cssEscapeUrl\(value: string\)/);
  assert.match(layout, /const stableAvatarUrl = await loadServerProfileAvatarDataUrl\(\)/);
  assert.match(layout, /if \(stableAvatarUrl\) \{[\s\S]*setAvatarUrl\(stableAvatarUrl\);[\s\S]*return;[\s\S]*\}/);
  assert.match(layout, /signed_avatar_url=used_as_fallback/);
  assert.match(layout, /if \(profile\.avatarUrl\) \{[\s\S]*setAvatarUrl\(profile\.avatarUrl\);[\s\S]*return;[\s\S]*\}/);
  assert.match(layout, /avatar_preserved=empty_lookup/);
  assert.match(layout, /fetch\("\/api\/profile\/avatar"/);
  assert.match(layout, /blobToDataUrl\(blob\)/);
  assert.match(layout, /reader\.readAsDataURL\(blob\)/);
  assert.match(layout, /fetch\("\/api\/profile\/identity-chip"/);
  assert.match(layout, /authorization: `Bearer \$\{token\}`/);
  assert.match(route, /getRequestUser\(request\)/);
  assert.match(route, /createSupabaseAdminClient\(\)/);
  assert.match(route, /getProfileAvatarPreview\(admin, profile\.avatar_path\)/);
  assert.match(route, /"Cache-Control": "no-store"/);
  assert.match(avatarRoute, /getRequestUser\(request\)/);
  assert.match(avatarRoute, /AVATAR_BUCKET_CANDIDATES/);
  assert.match(avatarRoute, /admin\.storage\.from\(bucket\)\.download\(avatarPath\)/);
  assert.match(avatarRoute, /"Content-Type": file\.data\.type \|\| "image\/jpeg"/);
});

test("document-oriented records avoid forced monetary structure and task linking is optional", () => {
  const workspace = fs.readFileSync(path.join(root, "components/records/UniversalRecordWorkspace.tsx"), "utf8");
  const fieldDictionary = fs.readFileSync(path.join(root, "lib/assets/fieldDictionary.ts"), "utf8");
  const createAsset = fs.readFileSync(path.join(root, "lib/assets/createAsset.ts"), "utf8");

  assert.match(workspace, /isNarrativeDocumentWorkspace/);
  assert.match(workspace, /Add a short note or upload a document before saving this record/);
  assert.match(workspace, /Add details or upload a document/);
  assert.match(workspace, /Expression of wishes title/);
  assert.match(workspace, /Narrative instructions/);
  assert.match(workspace, /Document or note type/);
  assert.match(workspace, /!isTrustedContacts && !isNarrativeDocumentWorkspace/);
  assert.match(workspace, /value_minor: isTrustedContacts \|\| isNarrativeDocumentWorkspace \? null/);
  assert.match(workspace, /currency_code: isTrustedContacts \|\| isNarrativeDocumentWorkspace \? null/);
  assert.match(workspace, /isNarrativeDocumentWorkspace \? null/);
  assert.match(workspace, /multiple/);
  assert.match(fieldDictionary, /key: "related_asset_id"[\s\S]*required: false/);
  assert.doesNotMatch(createAsset, /Related Asset \/ Record is required/);
});

test("shared consumer workflow controls support structured capture and assisted upload confirmation", () => {
  const controls = fs.readFileSync(path.join(root, "components/forms/asset/AssetFormControls.tsx"), "utf8");
  const configFields = fs.readFileSync(path.join(root, "components/forms/asset/ConfigDrivenAssetFields.tsx"), "utf8");
  const documentsWorkspace = fs.readFileSync(path.join(root, "components/documents/DocumentsWorkspace.tsx"), "utf8");
  const onboarding = fs.readFileSync(path.join(root, "app/onboarding/OnboardingPageClient.tsx"), "utf8");

  assert.match(controls, /export function RequiredIndicator/);
  assert.match(controls, /aria-label="Required"/);
  assert.match(controls, /export function OtherSelectInput/);
  assert.match(controls, /Choose the closest option\. Select Other only when none fit\./);
  assert.match(controls, /export function SegmentedControl/);
  assert.match(controls, /role="group"/);
  assert.match(controls, /export function ExtractionConfirmationPanel/);
  assert.match(controls, /Extracted values are a starting point only/);
  assert.match(controls, /helperText\?: string/);
  assert.match(controls, /role="alert"/);
  assert.match(configFields, /field\.inputType === "select" && field\.supportsOther && field\.otherKey/);
  assert.match(configFields, /<OtherSelectInput/);
  assert.match(configFields, /required=\{field\.required\}/);
  assert.doesNotMatch(configFields, /showOther && false/);
  assert.match(documentsWorkspace, /<ExtractionConfirmationPanel/);
  assert.match(documentsWorkspace, /Any extracted details remain editable before they become part of your vault/);
  assert.match(documentsWorkspace, /helperText=\{selectedKind === "photo"/);
  assert.match(documentsWorkspace, /disabled=\{saving \|\| !pendingFile\}/);
  assert.match(onboarding, /PlatformSection/);
  assert.match(onboarding, /Set up your vault in stages/);
  assert.match(onboarding, /Tasks and reminders stay inside Action Centre/);
  assert.match(onboarding, /onboardingMilestones/);
});
