import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();

test("dashboard overview cards use compact shared summary cards with icon-only review actions", () => {
  const dashboardPage = fs.readFileSync(path.join(root, "app/(app)/dashboard/page.tsx"), "utf8");
  const summaryCard = fs.readFileSync(path.join(root, "app/(app)/components/dashboard/DashboardAssetSummaryCard.tsx"), "utf8");
  const actionQueue = fs.readFileSync(path.join(root, "app/(app)/components/dashboard/ActionQueuePanel.tsx"), "utf8");
  const dashboardRender = dashboardPage.slice(
    dashboardPage.indexOf('return (\n    <div style={{ display: "grid", gap: 14 }}>'),
    dashboardPage.indexOf("function ReadinessSnapshot"),
  );

  assert.match(dashboardPage, /value=\{String\(financeRecordCount\)\}/);
  assert.match(dashboardPage, /value=\{String\(propertyRecordCount\)\}/);
  assert.match(dashboardPage, /value=\{String\(businessRecordCount\)\}/);
  assert.doesNotMatch(dashboardPage, /value=\{financialSummary\.valueText\}/);
  assert.doesNotMatch(dashboardPage, /value=\{propertySummary\.valueText\}/);
  assert.doesNotMatch(dashboardPage, /value=\{businessSummary\.valueText\}/);
  assert.match(dashboardPage, /function useDashboardState\(input: DashboardStateInput\): DashboardState/);
  assert.match(dashboardPage, /<ActionQueuePanel items=\{dashboardState\.actions\.items\} context=\{dashboardState\.actions\.context\} onAction=\{handleAction\} \/>/);
  assert.match(dashboardPage, /function filterConsumerDashboardBlockers/);
  assert.match(dashboardPage, /requiredRole !== "admin"/);
  assert.match(dashboardPage, /!item\.href\.startsWith\("\/internal\/"\)/);
  assert.match(dashboardPage, /type DashboardContactRow = \{/);
  assert.match(dashboardPage, /role: DashboardContactRole/);
  assert.match(dashboardPage, /status: DashboardContactStatus/);
  assert.match(dashboardPage, /actions: DashboardContactAction\[\]/);
  assert.match(dashboardPage, /function normalizeDashboardContactRows/);
  assert.match(dashboardPage, /contacts: \{\s*rows: normalizedContactRows,/);
  assert.match(dashboardPage, /documents: \{\s*items: dashboardDocumentItems,\s*storedCount: storedDocumentCount,/);
  assert.match(dashboardPage, /const documentCoverage = useMemo/);
  assert.match(dashboardPage, /coverage: documentCoverage/);
  assert.match(dashboardPage, /type ExecutorLegalReadinessModel = \{/);
  assert.match(dashboardPage, /type ExecutorLegalReadinessStatusLevel = "Not started" \| "Incomplete" \| "At risk" \| "Ready"/);
  assert.match(dashboardPage, /executorAssigned: boolean/);
  assert.match(dashboardPage, /executorAccepted: boolean/);
  assert.match(dashboardPage, /willPresent: boolean/);
  assert.match(dashboardPage, /willUploaded: boolean/);
  assert.match(dashboardPage, /keyDocumentsPresent: boolean/);
  assert.match(dashboardPage, /supportingLegalInfoPresent: boolean/);
  assert.match(dashboardPage, /powerOfAttorneyPresent: boolean/);
  assert.match(dashboardPage, /contactsComplete: boolean/);
  assert.match(dashboardPage, /identityVerified: boolean/);
  assert.match(dashboardPage, /function buildExecutorLegalReadinessState/);
  assert.match(dashboardPage, /function getExecutorLegalReadinessStatusLevel/);
  assert.match(dashboardPage, /if \(!model\.executorAssigned\) return "Not started"/);
  assert.match(dashboardPage, /if \(!model\.willPresent && !model\.willUploaded\) return "Incomplete"/);
  assert.match(dashboardPage, /return "At risk"/);
  assert.match(dashboardPage, /return "Ready"/);
  assert.match(dashboardPage, /legalReadiness: \{/);
  assert.match(dashboardPage, /Estate Readiness/);
  assert.match(dashboardPage, /ReadinessSnapshot/);
  assert.match(dashboardPage, /ReadinessUploadAction/);
  assert.match(dashboardPage, /executorSummary/);
  assert.match(dashboardPage, /documentSummary/);
  assert.match(dashboardPage, /supportingLegalInfo: supportingLegalInfoPresent \? "Recorded" : "Not added"/);
  assert.match(dashboardPage, /powerOfAttorney: powerOfAttorneyPresent \? "Recorded" : "Not added"/);
  assert.match(dashboardPage, /function hasSupportingLegalInfoRecord/);
  assert.match(dashboardPage, /function hasPowerOfAttorneyRecord/);
  assert.match(dashboardPage, /reviewRecommended/);
  assert.match(dashboardPage, /Review recommended/);
  assert.match(dashboardPage, /function renderReadinessActionPanel/);
  assert.match(dashboardPage, /readinessKey: "willUploaded"/);
  assert.match(dashboardPage, /buildReviewPanelFromReadinessItem/);
  assert.match(dashboardPage, /Full contact management/);
  assert.match(dashboardPage, /Upload identity document/);
  assert.match(dashboardPage, /Upload financial\/property document/);
  assert.match(dashboardPage, /<AttachmentGallery[\s\S]*items=\{dashboardState\.documents\.items\}/);
  assert.match(dashboardPage, /Multiple files are supported there/);
  assert.match(dashboardPage, /Mark reviewed is not stored separately yet/);
  assert.match(dashboardPage, /not legal advice/);
  assert.match(dashboardPage, /does not validate legal authenticity/);
  assert.doesNotMatch(dashboardPage, /valid legal document|legally valid|legally binding/);
  assert.match(dashboardPage, /DASHBOARD_KEY_DOCUMENT_CATEGORIES/);
  assert.match(dashboardPage, /No documents uploaded yet\./);
  assert.match(dashboardPage, /Only 1 document uploaded/);
  assert.match(dashboardPage, /Key documents missing:/);
  assert.match(dashboardPage, /<AttachmentGallery[\s\S]*items=\{dashboardState\.documents\.items\}/);
  assert.match(dashboardPage, /completeness: \{\s*items: vaultCompletenessItems,/);
  assert.match(dashboardPage, /blockers: \{\s*items: blockingState\.filter/);
  assert.match(dashboardPage, /signals: DashboardInsightSignal\[\]/);
  assert.match(dashboardPage, /function buildDashboardInsightSignals/);
  assert.match(dashboardPage, /const handleSetupStepAction = useCallback/);
  assert.match(dashboardPage, /function buildReviewPanelFromSetupStep/);
  assert.doesNotMatch(dashboardPage, /<a key=\{step\.key\} href=\{step\.href\}/);
  assert.doesNotMatch(dashboardPage, /href=\{dashboardState\.actions\.nextSetupStep\.href\}/);
  assert.match(dashboardPage, /type: "missing_executor"/);
  assert.match(dashboardPage, /type: "missing_will"/);
  assert.match(dashboardPage, /type: "profile_incomplete"/);
  assert.match(dashboardPage, /type: "missing_financial_records"/);
  assert.match(dashboardPage, /type: "missing_documents"/);
  assert.match(dashboardPage, /type: "review_overdue"/);
  assert.match(dashboardPage, /const handleAction = useCallback\(\(actionKey: string\)/);
  assert.match(dashboardPage, /deriveBlockingState\(/);
  assert.match(dashboardPage, /inlineSummary/);
  assert.match(dashboardPage, /hideItems/);
  assert.match(dashboardPage, /actionIcon="open_in_new"/);
  assert.match(summaryCard, /<IconButton/);
  assert.match(summaryCard, /actionIcon = "open_in_new"/);
  assert.match(summaryCard, /<span style=\{valueStyle\}>/);
  assert.match(summaryCard, /<span style=\{detailStyle\}>/);
  assert.match(actionQueue, /Action Centre/);
  assert.match(actionQueue, /Critical actions/);
  assert.match(actionQueue, /Recommended actions/);
  assert.match(actionQueue, /Your tasks/);
  assert.match(actionQueue, /Things to do,\s*reminders, and user-created tasks live here instead of the dashboard overview/);
  assert.match(actionQueue, /Completed/);
  assert.match(actionQueue, /type ActionCentreTaskType = "user_created" \| "system_generated" \| "reminder"/);
  assert.match(actionQueue, /relatedEntity\?: string/);
  assert.match(actionQueue, /createdAt\?: string \| null/);
  assert.match(actionQueue, /task:complete:\$\{task\.id\}/);
  assert.match(actionQueue, /task:open:\$\{task\.id\}/);
  assert.match(actionQueue, /function taskDuplicatesAction/);
  assert.match(actionQueue, /task\.type !== "system_generated"/);
  assert.match(actionQueue, /function getTaskDedupeKey/);
  assert.match(dashboardPage, /relatedEntity: String\(metadata\["related_asset_label"\]/);
  assert.doesNotMatch(dashboardPage, /showTaskCard/);
  assert.doesNotMatch(dashboardPage, /taskSummary/);
  assert.doesNotMatch(dashboardPage, /title="Tasks"/);
  assert.match(dashboardPage, /showFinancialCard \|\| showLegalCard \|\| showPropertyCard \|\| showBusinessCard \|\| showDigitalCard \|\| showPossessionsCard/);
  assert.doesNotMatch(dashboardPage, /showFinancialCard \|\| showLegalCard \|\| showPropertyCard \|\| showBusinessCard \|\| showDigitalCard \|\| showPossessionsCard \|\| showTaskCard/);
  assert.match(dashboardPage, /categoryKey !== "tasks"/);
  assert.match(dashboardPage, /markDashboardTaskComplete/);
  assert.match(dashboardPage, /tasks: actionCentreTasks/);
  assert.match(actionQueue, /All up to date/);
  assert.match(actionQueue, /notifications_active/);
  assert.match(actionQueue, /contacts still need to accept invitations\./);
  assert.match(actionQueue, /contacts are ready for invite emails\./);
  assert.match(actionQueue, /assignment_late/);
  assert.match(actionQueue, /stageChipStyle/);
  assert.match(actionQueue, /buildSectionSummary/);
  assert.match(actionQueue, /type ActionPriorityLevel = "Critical" \| "High" \| "Medium" \| "Low"/);
  assert.match(actionQueue, /dashboard-add-executor/);
  assert.match(actionQueue, /estateReadiness/);
  assert.match(actionQueue, /dashboard-upload-will/);
  assert.match(actionQueue, /dashboard-add-key-documents/);
  assert.match(actionQueue, /Will information is a core readiness signal/);
  assert.match(actionQueue, /return "will"/);
  assert.match(actionQueue, /return "key-documents"/);
  assert.match(actionQueue, /priorityPillStyle/);
  assert.match(actionQueue, /aria-expanded=\{isOpen\}/);
  assert.match(actionQueue, /useState<ActionCentreSection\["key"\] \| null>\(null\)/);
  assert.match(actionQueue, /toggleSection\(section\.key\)/);
  assert.match(actionQueue, /onAction\(item.actionKey\)/);
  assert.doesNotMatch(actionQueue, /supportingLegalInfoPresent|powerOfAttorneyPresent/);
  assert.doesNotMatch(dashboardPage, /ContactInvitationManager mode="dashboard"/);
  assert.doesNotMatch(dashboardPage, /overallVaultProgress/);
  assert.doesNotMatch(dashboardPage, /progressTrackStyle/);
  assert.doesNotMatch(dashboardPage, /% ready|% complete/);
  assert.match(dashboardPage, /storedDocumentCount/);
  assert.match(dashboardRender, /<h2 style=\{\{ margin: 0, fontSize: 18 \}\}>Overview<\/h2>/);
  assert.match(dashboardRender, /<ActionQueuePanel items=\{dashboardState\.actions\.items\} context=\{dashboardState\.actions\.context\} onAction=\{handleAction\} \/>/);
  assert.match(dashboardRender, /aria-label="Estate readiness summary"/);
  assert.doesNotMatch(dashboardRender, /Get started with your vault/);
  assert.doesNotMatch(dashboardRender, /<h2 style=\{\{ margin: 0, fontSize: 18 \}\}>Next steps<\/h2>/);
  assert.doesNotMatch(dashboardRender, /People you trust/);
  assert.doesNotMatch(dashboardRender, /aria-label="Vault completeness"/);
  assert.doesNotMatch(dashboardRender, /aria-label="Recent documents"/);
  assert.doesNotMatch(dashboardRender, /setupStepsGridStyle|completenessGridStyle|documentCategoryGridStyle|readinessGridStyle/);
  assert.doesNotMatch(dashboardRender, /<ReadinessSnapshot|<ReadinessUploadAction|<AttachmentGallerySummary|<AttachmentGallery\s/);
  assert.ok(dashboardRender.indexOf(">Overview<") < dashboardRender.indexOf("<ActionQueuePanel"));
  assert.ok(dashboardRender.indexOf("<ActionQueuePanel") < dashboardRender.indexOf('aria-label="Estate readiness summary"'));
});

test("contacts keeps the fuller invitation management view while dashboard stays compact", () => {
  const contactsWorkspace = fs.readFileSync(path.join(root, "components/contacts/ContactsNetworkWorkspace.tsx"), "utf8");
  const invitationManager = fs.readFileSync(path.join(root, "app/(app)/components/dashboard/ContactInvitationManager.tsx"), "utf8");

  assert.match(contactsWorkspace, /<ContactInvitationManager[\s\S]*mode="full"[\s\S]*selectedContactId=\{selectedContactId\}[\s\S]*selectedContactProfile=\{selectedContact\}[\s\S]*\/>/);
  assert.match(invitationManager, /mode\?: "full" \| "dashboard"/);
  assert.match(invitationManager, /selectedContactId\?: string/);
  assert.match(invitationManager, /Owner notes/);
  assert.match(invitationManager, /Open Contacts/);
  assert.match(invitationManager, /buildContactsWorkspaceHref/);
  assert.doesNotMatch(invitationManager, /Invitation sent and awaiting activation/);
  assert.doesNotMatch(invitationManager, /Signed in and verified\./);
  assert.doesNotMatch(invitationManager, />Resend<\/th>/);
  assert.match(invitationManager, /function canSendInvite/);
  assert.match(invitationManager, /function canResendInvite/);
});

test("shared attachment gallery uses icon buttons with tooltips instead of ad hoc text action buttons", () => {
  const attachmentGallery = fs.readFileSync(path.join(root, "components/documents/AttachmentGallery.tsx"), "utf8");

  assert.match(attachmentGallery, /function AttachmentVisual/);
  assert.match(attachmentGallery, /function AttachmentActionButton/);
  assert.match(attachmentGallery, /label="View"/);
  assert.match(attachmentGallery, /label="Download"/);
  assert.match(attachmentGallery, /label="Print"/);
  assert.match(attachmentGallery, /label="Replace"/);
  assert.match(attachmentGallery, /label="Remove"/);
  assert.match(attachmentGallery, /icon="visibility"/);
  assert.match(attachmentGallery, /icon="download"/);
  assert.match(attachmentGallery, /icon="open_in_new"/);
  assert.match(attachmentGallery, /icon="print"/);
  assert.match(attachmentGallery, /icon="delete"/);
  assert.match(attachmentGallery, /alt=\{visual\.alt\}/);
  assert.match(attachmentGallery, /kind === "image"/);
  assert.match(attachmentGallery, /kind === "pdf"/);
  assert.match(attachmentGallery, /kind === "word"/);
  assert.match(attachmentGallery, /kind === "spreadsheet"/);
  assert.match(attachmentGallery, /kind === "calendar"/);
  assert.match(attachmentGallery, /getFileIcon/);
  assert.match(attachmentGallery, /picture_as_pdf/);
  assert.match(attachmentGallery, /article/);
  assert.match(attachmentGallery, /table_chart/);
  assert.match(attachmentGallery, /calendar_month/);
  assert.match(attachmentGallery, /fileTypePillStyle/);
  assert.match(attachmentGallery, /statusLabel/);
  assert.match(attachmentGallery, /Uploaded \{formatDate\(item\.createdAt\)\}/);
  assert.doesNotMatch(attachmentGallery, /window\.open/);
  assert.doesNotMatch(attachmentGallery, /<IconButton/);
  assert.doesNotMatch(attachmentGallery, /style=\{miniGhostBtn\}/);
});

test("document-oriented records avoid forced monetary structure and task linking is optional", () => {
  const workspace = fs.readFileSync(path.join(root, "components/records/UniversalRecordWorkspace.tsx"), "utf8");
  const fieldDictionary = fs.readFileSync(path.join(root, "lib/assets/fieldDictionary.ts"), "utf8");
  const createAsset = fs.readFileSync(path.join(root, "lib/assets/createAsset.ts"), "utf8");

  assert.match(workspace, /isNarrativeDocumentWorkspace/);
  assert.match(workspace, /Add a short note or upload a document before saving this record/);
  assert.match(workspace, /Add details or upload a document/);
  assert.match(workspace, /Expression of wishes title/);
  assert.match(workspace, /Narrative instructions/);
  assert.match(workspace, /Document or note type/);
  assert.match(workspace, /!isTrustedContacts && !isNarrativeDocumentWorkspace/);
  assert.match(workspace, /value_minor: isTrustedContacts \|\| isNarrativeDocumentWorkspace \? null/);
  assert.match(workspace, /currency_code: isTrustedContacts \|\| isNarrativeDocumentWorkspace \? null/);
  assert.match(workspace, /isNarrativeDocumentWorkspace \? null/);
  assert.match(workspace, /multiple/);
  assert.match(fieldDictionary, /key: "related_asset_id"[\s\S]*required: false/);
  assert.doesNotMatch(createAsset, /Related Asset \/ Record is required/);
});
