export const publicEnv = {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || "",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "",
};

export const recommendedServerEnv = [
  "STRIPE_SECRET_KEY",
  "STRIPE_WEBHOOK_SECRET",
  "STRIPE_CUSTOMER_PORTAL_URL",
  "SUPABASE_SERVICE_ROLE_KEY",
  "AUTH_PROVIDER_ISSUER",
  "AUTH_PROVIDER_JWKS_URL",
  "GOOGLE_CLIENT_ID",
  "APPLE_CLIENT_ID",
] as const;
